#%RAML 1.0 Trait
headers:
  client_id:
    description: Client's Id
    displayName: Client Id
    required: true
    type: string
  client_secret:
    description: Client's Secret Id
    displayName: Client Secret
    required: true
    type: string